import { invoke } from '@tauri-apps/api/core';
import { Order, OrderItem, OrderPayment, OrderWithDetails } from '@/types/order';

/**
 * Order Management API - Tauri command wrappers
 */

// ============================================================================
// CRUD Operations
// ============================================================================

/**
 * Create a new order
 */
export async function createOrder(order: Order): Promise<Order> {
    return await invoke<Order>('create_order', { order });
}

/**
 * Get all orders with optional status filtering
 */
export async function getOrders(statusFilter?: 'draft' | 'completed'): Promise<Order[]> {
    return await invoke<Order[]>('get_orders', {
        statusFilter: statusFilter || null
    });
}

/**
 * Get a single order by ID with all details
 */
export async function getOrderById(orderId: string): Promise<OrderWithDetails | null> {
    return await invoke<OrderWithDetails | null>('get_order_by_id', { orderId });
}

/**
 * Get all orders for a specific supplier
 */
export async function getOrdersBySupplier(supplierId: string): Promise<Order[]> {
    return await invoke<Order[]>('get_orders_by_supplier', { supplierId });
}

/**
 * Update an existing order
 */
export async function updateOrder(order: Order): Promise<void> {
    await invoke('update_order', { order });
}

// ============================================================================
// Item Management
// ============================================================================

/**
 * Add an item to an order
 * Note: This automatically recalculates the order total
 */
export async function addOrderItem(item: OrderItem): Promise<void> {
    await invoke('add_order_item', { item });
}

/**
 * Update an order item
 * Note: This automatically recalculates the order total
 */
export async function updateOrderItem(item: OrderItem): Promise<void> {
    await invoke('update_order_item', { item });
}

/**
 * Remove an item from an order
 * Note: This automatically recalculates the order total
 */
export async function removeOrderItem(itemId: string, orderId: string): Promise<void> {
    await invoke('remove_order_item', { itemId, orderId });
}

// ============================================================================
// Payment Tracking
// ============================================================================

/**
 * Add a payment to an order
 * Note: This automatically recalculates payment status
 */
export async function addOrderPayment(payment: OrderPayment): Promise<void> {
    await invoke('add_order_payment', { payment });
}

/**
 * Get all payments for an order
 */
export async function getOrderPayments(orderId: string): Promise<OrderPayment[]> {
    return await invoke<OrderPayment[]>('get_order_payments', { orderId });
}

// ============================================================================
// Order Completion
// ============================================================================

/**
 * Complete an order and update inventory
 * This will:
 * - Change order status to 'completed'
 * - Update inventory quantities for all items
 * - Log inventory history events
 * - Log order completion in history
 */
export async function completeOrder(orderId: string): Promise<void> {
    await invoke('complete_order', { orderId });
}

// ============================================================================
// Helper Functions
// ============================================================================

/**
 * Generate a new order with default values
 */
export function createNewOrder(supplierId: string): Order {
    const now = new Date().toISOString();
    return {
        id: crypto.randomUUID(),
        order_number: '', // Will be auto-generated by backend
        supplier_id: supplierId,
        status: 'draft',
        payment_status: 'unpaid',
        total_amount: 0,
        paid_amount: 0,
        notes: undefined,
        created_at: now,
        updated_at: now,
        created_by: undefined,
    };
}

/**
 * Generate a new order item with default values
 */
export function createNewOrderItem(orderId: string, itemName: string = ''): OrderItem {
    return {
        id: crypto.randomUUID(),
        order_id: orderId,
        item_id: undefined,
        item_name: itemName,
        quantity: 1,
        unit_price: 0,
        total_price: 0,
        notes: undefined,
    };
}

/**
 * Generate a new payment with default values
 */
export function createNewPayment(orderId: string, amount: number, method: string = 'Cash'): OrderPayment {
    return {
        id: crypto.randomUUID(),
        order_id: orderId,
        amount,
        method,
        date: new Date().toISOString(),
        received_by: undefined,
        notes: undefined,
    };
}

/**
 * Calculate order item total
 */
export function calculateItemTotal(item: OrderItem): number {
    return item.quantity * item.unit_price;
}

/**
 * Calculate order total from items
 */
export function calculateOrderTotal(items: OrderItem[]): number {
    return items.reduce((sum, item) => sum + calculateItemTotal(item), 0);
}

/**
 * Determine payment status based on amounts
 */
export function determinePaymentStatus(totalAmount: number, paidAmount: number): 'unpaid' | 'partial' | 'paid' {
    if (paidAmount >= totalAmount) return 'paid';
    if (paidAmount > 0) return 'partial';
    return 'unpaid';
}
